// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ReportCreateBox: typeof import('./components/ReportCreateBox.vue')['default']
    ReportPanel: typeof import('./components/ReportPanel.vue')['default']
    ReportShowBox: typeof import('./components/ReportShowBox.vue')['default']
  }
}

export { }
