// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/apps/AppHeader.vue')['default']
    ArrayTagForm: typeof import('./components/ArrayTagForm.vue')['default']
    ReportEditBox: typeof import('./components/reports/ReportEditBox.vue')['default']
    ReportPanel: typeof import('./components/reports/ReportPanel.vue')['default']
    ReportShowBox: typeof import('./components/reports/ReportShowBox.vue')['default']
    SidePanel: typeof import('./components/apps/SidePanel.vue')['default']
    TagEditDialog: typeof import('./components/tags/TagEditDialog.vue')['default']
    TagTable: typeof import('./components/tags/TagTable.vue')['default']
  }
}

export { }
