// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/apps/AppHeader.vue')['default']
    ArrayTagForm: typeof import('./components/reports/ArrayTagForm.vue')['default']
    ConfigDrawer: typeof import('./components/apps/ConfigDrawer.vue')['default']
    ReportEditFullSheet: typeof import('./components/reports/sheets/ReportEditFullSheet.vue')['default']
    ReportEditSheet: typeof import('./components/reports/sheets/ReportEditSheet.vue')['default']
    ReportEditSimpleSheet: typeof import('./components/reports/sheets/ReportEditSimpleSheet.vue')['default']
    ReportPanel: typeof import('./components/reports/ReportPanel.vue')['default']
    ReportSearchDialog: typeof import('./components/timelines/ReportSearchDialog.vue')['default']
    ReportSearchPanel: typeof import('./components/timelines/ReportSearchPanel.vue')['default']
    ReportShowSheet: typeof import('./components/reports/sheets/ReportShowSheet.vue')['default']
    ReportTimeline: typeof import('./components/timelines/ReportTimeline.vue')['default']
    SidePanel: typeof import('./components/apps/SidePanel.vue')['default']
    TagEditDialog: typeof import('./components/tags/TagEditDialog.vue')['default']
    TagTable: typeof import('./components/tags/TagTable.vue')['default']
  }
}

export { }
